dist: xenial
os: linux
language: node_js
node_js:
- '6'
- '7'
- '8'
- '9'

addons:
  sauce_connect: true

jobs:
  include:
  - node_js: '6'
    env: BROWSER_NAME=chrome BROWSER_VERSION=latest
  - node_js: '6'
    env: BROWSER_NAME=chrome BROWSER_VERSION=29
  - node_js: '6'
    env: BROWSER_NAME=firefox BROWSER_VERSION=latest
  - node_js: '6'
    env: BROWSER_NAME=safari BROWSER_VERSION=latest
  - node_js: '6'
    env: BROWSER_NAME=safari BROWSER_VERSION=7
  - node_js: '6'
    env: BROWSER_NAME=ie BROWSER_VERSION=11
  - node_js: '6'
    env: BROWSER_NAME=ie BROWSER_VERSION=10
  - node_js: '6'
    env: BROWSER_NAME=ie BROWSER_VERSION=9
